// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGE6d5tfO37xFeEc5sgvdSG9avWtZ_a6Q',
    appId: '1:906233502667:web:62deb91e01e61bc812f44e',
    messagingSenderId: '906233502667',
    projectId: 'github-repo-search-f9f47',
    authDomain: 'github-repo-search-f9f47.firebaseapp.com',
    storageBucket: 'github-repo-search-f9f47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqUs5ZZC1PB-5xoBDE1e9bGB1_IHDgXJQ',
    appId: '1:906233502667:android:c29cd02ae12d20ea12f44e',
    messagingSenderId: '906233502667',
    projectId: 'github-repo-search-f9f47',
    storageBucket: 'github-repo-search-f9f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7GlfwgM1uHrIRhedEzV0xFYxkOYlXRrU',
    appId: '1:906233502667:ios:2c81a878786f7fb912f44e',
    messagingSenderId: '906233502667',
    projectId: 'github-repo-search-f9f47',
    storageBucket: 'github-repo-search-f9f47.appspot.com',
    iosClientId: '906233502667-51rlcr6dd8opqld5jri1pi3vift0im4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEngineerCodecheck.RunnerTests',
  );
}
